version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: build/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
