version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: build/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENV=${ENV}
      - PORT=${PORT}
      - DB_CONNECTION=${DB_CONNECTION}
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cart
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "user", "-d", "appdb" ]
      interval: 30s
      retries: 5
      timeout: 10s
      start_period: 10s

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
